import Head from "next/head";
import Image from "next/image";
import Link from 'next/link';
// import { Inter } from "next/font/google";
import { Button } from 'antd';

// const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Share OH | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* <div className={styles.description}>
          <div>
            <p>Welcome to Share OH!</p>
            <Link href="/login"><Button type="primary">Log In</Button></Link>
            <Link href="/frontpage"><Button type="primary">Front Page</Button></Link>
          </div>
        </div>
        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/share-oh.svg"
            alt="Share OH Logo"
            width={140}
            height={140}
            priority
          />
        </div> */}
      </main>
    </>
  );
}
