import Head from "next/head";
import Image from "next/image";

export default function Login() {
  return (
    <>
      <Head>
        <title>Share OH | Login</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div>
        <p>Voila! Logged In</p>
      </div>
    </>
  );
}
