import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Login() {
  return (
    <>
      <Head>
        <title>Share OH | Login</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <p>Get Started by Logging In</p>
          <div className={styles.center}>
            <Image
              className={styles.logo}
              src="/share-oh.svg"
              alt="Share OH Logo"
              width={140}
              height={140}
              priority
            />
          </div>
        </div>
      </main>
    </>
  );
}
